# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Samhita Marri
name: Samhita Marri
position: Graduate Research Assistant
description: >-
  I'm a PhD candidate at the University of Illinois Urbana-Champaign in Electrical and Computer Engineering. I am currently working as a research assistant at Distributed Autonomous Systems Laboratory with [Girish Chowdhary](http://daslab.illinois.edu/index.html#girish). I am passionate about applying computer vision, motion planning and multi-agent coordination in agricultural systems. Combinining these areas, my current research is on developing systems and techniques to perform plant manipulation tasks like harvesting, pruning and health monitoring autonomously. 


  Prior to joining UIUC, I graduated from Cornell University with an MEng degree in Electrical and Computer Engineering in May 2020, where I had the honor of working with [Joseph Skovira](https://skovira.ece.cornell.edu/) and [Hadas Kress-Gazit](https://www.verifiablerobotics.com/). I also interned for about a year at [Xallent](https://xallent.com/). Alongside my interests in agricultural robotics, some of my hobbies include Tae Kwon Do, cooking, painting, gaming and hiking. 

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://samhitamarri.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: m_samhita
github_username: samhita-m
google_scholar: jGcLaSIAAAAJ
google_analytics: G-18YGG0KM92

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
